[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
endless_framework = "0x1"
example_addr = "_"

[dependencies]
EndlessFramework = { local = "../../../framework/endless-framework" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
