[package]
name = "Examples"
version = "0.0.0"

[dependencies]
EndlessFramework = { local = "../../../framework/endless-framework" }
EndlessToken = { local = "../../../framework/endless-token" }

[addresses]
endless_framework = "0x1"
# replace the admin_addr with the actual admin address we created using CLI
admin_addr = "0xbeef"