[package]
name = "LargePackageExample"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
EndlessFramework = { local = "../../../framework/endless-framework" }

[addresses]
large_package_example = "_"
