[package]
name = "package_manager"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
EndlessFramework = { local = "../../framework/endless-framework" }

[addresses]
deployer = "_"
package = "_"
