[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
endless_framework = "0x1"

[dependencies]
EndlessFramework = { local = "../../../framework/endless-framework" }
EndlessToken = { local = "../../../framework/endless-token" }
