[package]
name = "Hero"
version = "0.0.0"

[addresses]
hero = "_"

[dependencies]
EndlessFramework = { local = "../../../framework/endless-framework" }
EndlessToken = { local = "../../../framework/endless-token" }
