# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.EndlessFramework]
local = '../../../framework/endless-framework' # <:!:manifest